version: '2'
services:

  postgres:
    image: postgres:9.5.2
    env_file: .env-postgres

  webserver:
    build:
      context: .
      dockerfile: Dockerfile

    links: [postgres]
    expose: ["8000"]
    env_file: .env

  queue_worker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: [webserver]
    command: /usr/src/app/docker-entrypoint-queue_worker.sh
    links: [postgres]
    env_file: .env
