version: '2'
services:

  postgres:
    image: postgres:9.5.2
    env_file: .env-postgres

  webserver:
    build:
      context: .
      dockerfile: Dockerfile

    depends_on: [postgres]
    links: [postgres]
    working_dir: /usr/src/app
    entrypoint: dockerize -wait tcp://postgres:5432 -timeout 10s
    command: ./docker-entrypoint-webserver.sh
    expose: ["8000"]
    env_file: .env
    restart: "always"

  queue_worker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: [webserver]
    links: [postgres]
    working_dir: /usr/src/app
    entrypoint: dockerize -wait tcp://postgres:5432 -timeout 10s
    command: ./docker-entrypoint-queue_worker.sh
    env_file: .env
    restart: "always"
