version: '2'
services:

  test:
    build:
      context: .
      dockerfile: Dockerfile

    working_dir: /usr/src/app
    entrypoint: dockerize -wait tcp://postgres:5432 -timeout 10s
    command: make requirements test
    links: [postgres]
    env_file: .env
